version: '3.8'

services:
  db:
    image: mysql:8.3
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 780525
      MYSQL_DATABASE: development


    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - api-network


  backend:
    image: sunwoo3856/backend:1
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: root
      DB_PASSWORD: 780525
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_NAME: development

    networks:
      - api-network
    ports:
      - "8081:8080"

  frontend:
    image: sunwoo3856/front:1
    depends_on:
      - backend
    ports:
      - "80:8081"
    networks:
      - api-network


networks:
  api-network:

volumes:
  db-data:


