version: '3.8'

services:
  db:
    image: mysql:8.3
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 780525
      MYSQL_DATABASE: development
      MYSQL_USER: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - api-network
    ports:
      - "3306:3306"


  backend:
    image: sunwoo3856/backend:latest
    depends_on:
      - config-server
      - db
    environment:
      DB_USER: root
      DB_PASSWORD: 780525
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: development
    networks:
      - api-network
    ports:
      - "8086:8086"

  diary-service:
    image: sunwoo3856/diary-service:latest
    depends_on:
      - config-server
      - db
    environment:
      DB_USER: root
      DB_PASSWORD: 780525
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: development
    networks:
      - api-network
    ports:
      - "8092:8092"

  frontend:
    image: sunwoo3856/front:latest
    depends_on:
      - backend
    ports:
      - "8888:80"
    networks:
      - api-network

  gateway:
    image: sunwoo3856/gateway:latest
    ports:
      - "80:8081"
      - "443:8081"
    networks:
      - api-network
    depends_on:
      - config-server

  config-server:
    image: sunwoo3856/config:latest
    ports:
      - "8087:8087"
    networks:
      - api-network

  authentication:
    image: sunwoo3856/authentication:latest
    ports:
      - "8084:8084"
    networks:
      - api-network
    environment:
      DB_USER: root
      DB_PASSWORD: 780525
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: development
    depends_on:
      - config-server
      - db

  eureka:
    image: sunwoo3856/eureka:latest
    ports:
      - "8090:8090"
    networks:
      - api-network
    depends_on:
      - config-server

networks:
  api-network:


volumes:
  db-data:


