spring:
  application:
    name: backend
  profiles:
    active: dev
  config:
    import: "configserver:http://config-server:8087"
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 10000
        max-attempts: 5
        multiplier: 1.5
      request-connect-timeout: 2000
      request-read-timeout: 10000
server:
  port: 8086
#encrypt:
#  key: ${ENCRYPT_KEY}
