spring:
  application:
    name: backend
  profiles:
    active: dev
  config:
    import: "configserver:http://192.168.0.154:8087"
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 10000
        max-attempts: 5
        multiplier: 1.5
      request-connect-timeout: 2000
      request-read-timeout: 10000

#encrypt:
#  key: ${ENCRYPT_KEY}
